# Prometheus (AppCo variant)
alertmanager:
  enabled: false
  service:
    type: NodePort

# Disable kube-state-metrics — not part of the CVE comparison
kubeStateMetrics:
  enabled: false

global:
  imagePullSecrets:
  - application-collection
