alertmanager:
  enabled: false
configmapReload:
  prometheus:
    image:
      tag: 0.90.1-14.4
global:
  imagePullSecrets:
    - application-collection
kubeStateMetrics:
  enabled: false
persistence:
  resources:
    requests:
      storage: 1Gi
server:
  image:
    tag: 3.11.2-1.4
  ingress:
    enabled: true
    hosts:
      - prometheus-appco.localhost
    ingressClassName: traefik
    path: /
  persistentVolume:
    size: 1Gi
