apiVersion: v1
kind: Service
metadata:
  name: message-wall-appco
  # deployed in default namespace alongside AppCo services
spec:
  selector:
    app: message-wall-appco
  ports:
    - port: 3000
      targetPort: 3000
