# values-dev.yaml — Configuration dev locale
global:
  imagePullSecrets:
    - application-collection

auth:
  username: demo
  password: demo
  database: demo
  
primary:
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi